# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d3c24d9c894aec7a2059afe3ce4669420d84ba3e2d30c0d756f83458d6e8d6ac7ea39678dd4af4bad6724584b64e9b8a5af16159b391557a9a82fbd4045b58

test:
  secret_key_base: 4527f029d6934aea395175aba55df4c0dac8a77000f1f3323ef098d1e9ea605c8f4390542ddf9ae355063fc0dbc659da43688ed2b8eb2a9df5a7ef27c5868283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
